# After installing Docker Desktop, run this command in the terminal to start the PostgreSQL container:
# docker run --name url-shortener-db -e POSTGRES_PASSWORD=1234 -p 5432:5432 -d postgres

version: '3.8'

services:
  db:
    image: postgres
    container_name: url-shortener-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: